config/routes.rb
Rails.application.routes.draw do
  resources :eigyosyos

  root :to => 'descriptions#index'
  
  resources :zetsufudaichos

  get 'naisenchosahyou/index'

  get 'map/index'

  resources :descriptions

get 'kofus/:id/show_one' => 'kofus#show_one' , as: 'show_one'
  
  resources :riyu_okunais

  resources :riyu_monshins

  resources :chosajisseki_codes

  resources :chosakekka_codes

  resources :zaitakus

  resources :tenkis

  resources :jyoutai_umufukanous

  resources :jyoutai_umumijisshis

  resources :jyoutai_umus

  resources :sokuteis

  resources :monshins

  resources :okugais

  resources :okunais

  resources :tenkenkekkas

  resources :houmons

  resources :kofus

  resources :keiyakus
 
  resources :chosains

  get 'mikofu_keiyakus' => 'keiyakus#mikofuindex'

  post 'create_kofus' => 'kofus#addKofus'
 
  resources :logindatas, only: [:create, :destroy]
  get    '/signin(/:kyoukaicode)'  => 'logindatas#new' , as: 'signin'
  delete '/signout' => 'logindatas#destroy'

  get 'chosains/eigyosyo_mem/:code' => 'chosains#eigyosyo_mem'

end

app/models/chosain.rb
class Chosain < ActiveRecord::Base
  has_many :kofus
  belongs_to :eigyosyo, :foreign_key => 'kyoukaicode'
end

app/models/description.rb
class Description < ActiveRecord::Base
end

app/models/eigyosyo.rb
class Eigyosyo < ActiveRecord::Base
  self.primary_key="kyoukaicode"
  has_many :chosains
end

app/models/houmon.rb
class Houmon < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :kofu
  has_one    :tenkenkekka
  accepts_nested_attributes_for :tenkenkekka
  belongs_to :tenko  , :class_name => "Tenki" , :foreign_key => "tenki"
  belongs_to :zaitakufuzai , :class_name => "Zaitaku" , :foreign_key => "zaitaku_jotai"
  
  include Common
  after_commit :dump 
end

app/models/jyoutai_umu.rb
class JyoutaiUmu < ActiveRecord::Base
end

app/models/keiyaku.rb
class Keiyaku < ActiveRecord::Base
  has_many :kofus
end

app/models/kofu.rb
class Kofu < ActiveRecord::Base
  belongs_to :keiyaku
  belongs_to :chosain
  has_many :houmons
  belongs_to :chosajisseki , :class_name => "ChosajissekiCode" , :foreign_key => "newest_chosajisseki_code"

  include Common
  after_commit :dump
end

app/models/monshin.rb
class Monshin < ActiveRecord::Base
  belongs_to :tenkenkekka
  belongs_to :monshin_jisshi_umu , :class_name => "JyoutaiUmu" , :foreign_key => "jisshi_umu"  
  belongs_to :mononifurebiribiri_umumijisshi , :class_name => "JyoutaiUmumijisshi" , :foreign_key => "mononifurebiribiri_umumi"
  belongs_to :zokaichiku_umumijisshi , :class_name => "JyoutaiUmumijisshi" , :foreign_key => "zoukaichiku_umumi"
  belongs_to :mijisshiriyu_list , :class_name => "RiyuMonshin" , :foreign_key => "mijisshi_riyu"

  include Common
  after_commit :dump 
end

app/models/okugai.rb
class Okugai < ActiveRecord::Base
  belongs_to :tenkenkekka
  belongs_to :toritsukezetsuen , :class_name => "JyoutaiUmufukanou" , :foreign_key => "toritsukezetsuen_ryohifuno"
  belongs_to :tabutsurikaku , :class_name => "JyoutaiUmufukanou" , :foreign_key => "tabutsurikaku_ryohifuno"

  include Common
  after_commit :dump 
end

app/models/okunai.rb
class Okunai < ActiveRecord::Base
  belongs_to :tenkenkekka
  belongs_to :okunai_jisshi_umu , :class_name => "JyoutaiUmu" , :foreign_key => "jisshi_umu"  
  belongs_to :bundenbanhason , :class_name => "JyoutaiUmu" , :foreign_key => "bundenbanhason_umu"
  belongs_to :juudenburosyutsu , :class_name => "JyoutaiUmu" , :foreign_key => "juudenburosyutsu_umu"
  belongs_to :mijisshiriyu_list , :class_name => "RiyuOkunai" , :foreign_key => "mijisshi_riyu"

  include Common
  after_commit :dump
end

app/models/riyu_monshin.rb
class RiyuMonshin < ActiveRecord::Base
end

app/models/riyu_okunai.rb
class RiyuOkunai < ActiveRecord::Base
end

app/models/sokutei.rb
class Sokutei < ActiveRecord::Base
   belongs_to :tenkenkekka

  include Common
  after_commit :dump 
end

app/models/tenkenkekka.rb
class Tenkenkekka < ActiveRecord::Base
  belongs_to :houmon
  has_one    :monshin
  accepts_nested_attributes_for :monshin
  has_one    :okunai
  accepts_nested_attributes_for :okunai
  has_one    :okugai
  accepts_nested_attributes_for :okugai
  has_one    :sokutei
  accepts_nested_attributes_for :sokutei
  belongs_to :chosakekka  , :class_name => "ChosakekkaCode" , :foreign_key => "chosakekka_code"
  belongs_to :chosajisseki , :class_name => "ChosajissekiCode" , :foreign_key => "chosajisseki_code"

  include Common
  after_commit :dump 
end

app/models/tenki.rb
class Tenki < ActiveRecord::Base
end

app/models/zaitaku.rb
class Zaitaku < ActiveRecord::Base
end

app/models/zetsufudaicho.rb
class Zetsufudaicho < ActiveRecord::Base
end

app/controllers/sokuteis_controller.rb
class SokuteisController < ApplicationController
  before_action :set_sokutei, only: [:show, :edit, :update, :destroy]

  # GET /sokuteis
  # GET /sokuteis.json
  def index
    @sokuteis = Sokutei.all
  end

  # GET /sokuteis/1
  # GET /sokuteis/1.json
  def show
  end

  # GET /sokuteis/new
  def new
    @sokutei = Sokutei.new
  end

  # GET /sokuteis/1/edit
  def edit
  end

  # POST /sokuteis
  # POST /sokuteis.json
  def create
    @sokutei = Sokutei.new(sokutei_params)

    respond_to do |format|
      if @sokutei.save
        format.html { redirect_to @sokutei, notice: 'Sokutei was successfully created.' }
        format.json { render :show, status: :created, location: @sokutei }
      else
        format.html { render :new }
        format.json { render json: @sokutei.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sokuteis/1
  # PATCH/PUT /sokuteis/1.json
  def update
    respond_to do |format|
      if @sokutei.update(sokutei_params)
        format.html { redirect_to @sokutei, notice: 'Sokutei was successfully updated.' }
        format.json { render :show, status: :ok, location: @sokutei }
      else
        format.html { render :edit }
        format.json { render json: @sokutei.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sokuteis/1
  # DELETE /sokuteis/1.json
  def destroy
    @sokutei.destroy
    respond_to do |format|
      format.html { redirect_to sokuteis_url, notice: 'Sokutei was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sokutei
      @sokutei = Sokutei.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sokutei_params
      params.require(:sokutei).permit(:kairo_su, :roueidenryu_ikkatsu, :zetsuenteikou_ikkatsu)
    end
end

app/helpers/houmons_helper.rb
module HoumonsHelper
end

app/helpers/kofus_helper.rb
module KofusHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/sokuteis_helper.rb
module SokuteisHelper
end

app/helpers/tenkis_helper.rb
module TenkisHelper
end

app/views/sokuteis/_form.html.erb
<%= form_for(@sokutei) do |f| %>
  <% if @sokutei.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sokutei.errors.count, "error") %> prohibited this sokutei from being saved:</h2>

      <ul>
      <% @sokutei.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "回路数" %><br>
    <%= f.number_field :kairo_su %>
  </div>
  <div class="field">
    <%= f.label "漏洩電流一括値" %><br>
    <%= f.text_field :roueidenryu_ikkatsu %>mA
  </div>
  <div class="field">
    <%= f.label "絶縁抵抗一括値" %><br>
    <%= f.text_field :zetsuenteikou_ikkatsu %>MΩ
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sokuteis/edit.html.erb
<h1>Editing sokutei</h1>

<%= render 'form' %>

<%= link_to 'Show', @sokutei %> |
<%= link_to 'Back', sokuteis_path %>

app/views/sokuteis/index.html.erb
<h1>Listing sokuteis</h1>

<table>
  <thead>
    <tr>
      <th>Kairo su</th>
      <th>Roueidenryu ikkatsu</th>
      <th>Zetsuenteikou ikkatsu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sokuteis.each do |sokutei| %>
      <tr>
        <td><%= sokutei.kairo_su %></td>
        <td><%= sokutei.roueidenryu_ikkatsu %></td>
        <td><%= sokutei.zetsuenteikou_ikkatsu %></td>
        <td><%= link_to 'Show', sokutei %></td>
        <td><%= link_to 'Edit', edit_sokutei_path(sokutei) %></td>
        <td><%= link_to 'Destroy', sokutei, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sokutei', new_sokutei_path %>

app/views/sokuteis/new.html.erb
<h1>New sokutei</h1>

<%= render 'form' %>

<%= link_to 'Back', sokuteis_path %>

app/views/sokuteis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>回路数</strong>
  <%= @sokutei.kairo_su %>
</p>

<p>
  <strong>漏洩電流一括値</strong>
  <%= @sokutei.roueidenryu_ikkatsu %>mA
</p>

<p>
  <strong>絶縁抵抗一括値</strong>
  <%= @sokutei.zetsuenteikou_ikkatsu %>MΩ
</p>

<%= link_to 'Edit', edit_sokutei_path(@sokutei) %> |
<%= link_to 'Back', sokuteis_path %>