config/routes.rb
Rails.application.routes.draw do
  resources :eigyosyos

  root :to => 'descriptions#index'
  
  resources :zetsufudaichos

  get 'naisenchosahyou/index'

  get 'map/index'

  resources :descriptions

get 'kofus/:id/show_one' => 'kofus#show_one' , as: 'show_one'
  
  resources :riyu_okunais

  resources :riyu_monshins

  resources :chosajisseki_codes

  resources :chosakekka_codes

  resources :zaitakus

  resources :tenkis

  resources :jyoutai_umufukanous

  resources :jyoutai_umumijisshis

  resources :jyoutai_umus

  resources :sokuteis

  resources :monshins

  resources :okugais

  resources :okunais

  resources :tenkenkekkas

  resources :houmons

  resources :kofus

  resources :keiyakus
 
  resources :chosains

  get 'mikofu_keiyakus' => 'keiyakus#mikofuindex'

  post 'create_kofus' => 'kofus#addKofus'
 
  resources :logindatas, only: [:create, :destroy]
  get    '/signin(/:kyoukaicode)'  => 'logindatas#new' , as: 'signin'
  delete '/signout' => 'logindatas#destroy'

  get 'chosains/eigyosyo_mem/:code' => 'chosains#eigyosyo_mem'

end

app/models/chosain.rb
class Chosain < ActiveRecord::Base
  has_many :kofus
  belongs_to :eigyosyo, :foreign_key => 'kyoukaicode'
end

app/models/chosakekka_code.rb
class ChosakekkaCode < ActiveRecord::Base
end

app/models/description.rb
class Description < ActiveRecord::Base
end

app/models/eigyosyo.rb
class Eigyosyo < ActiveRecord::Base
  self.primary_key="kyoukaicode"
  has_many :chosains
end

app/models/houmon.rb
class Houmon < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :kofu
  has_one    :tenkenkekka
  accepts_nested_attributes_for :tenkenkekka
  belongs_to :tenko  , :class_name => "Tenki" , :foreign_key => "tenki"
  belongs_to :zaitakufuzai , :class_name => "Zaitaku" , :foreign_key => "zaitaku_jotai"
  
  include Common
  after_commit :dump 
end

app/models/jyoutai_umu.rb
class JyoutaiUmu < ActiveRecord::Base
end

app/models/keiyaku.rb
class Keiyaku < ActiveRecord::Base
  has_many :kofus
end

app/models/kofu.rb
class Kofu < ActiveRecord::Base
  belongs_to :keiyaku
  belongs_to :chosain
  has_many :houmons
  belongs_to :chosajisseki , :class_name => "ChosajissekiCode" , :foreign_key => "newest_chosajisseki_code"

  include Common
  after_commit :dump
end

app/models/monshin.rb
class Monshin < ActiveRecord::Base
  belongs_to :tenkenkekka
  belongs_to :monshin_jisshi_umu , :class_name => "JyoutaiUmu" , :foreign_key => "jisshi_umu"  
  belongs_to :mononifurebiribiri_umumijisshi , :class_name => "JyoutaiUmumijisshi" , :foreign_key => "mononifurebiribiri_umumi"
  belongs_to :zokaichiku_umumijisshi , :class_name => "JyoutaiUmumijisshi" , :foreign_key => "zoukaichiku_umumi"
  belongs_to :mijisshiriyu_list , :class_name => "RiyuMonshin" , :foreign_key => "mijisshi_riyu"

  include Common
  after_commit :dump 
end

app/models/okugai.rb
class Okugai < ActiveRecord::Base
  belongs_to :tenkenkekka
  belongs_to :toritsukezetsuen , :class_name => "JyoutaiUmufukanou" , :foreign_key => "toritsukezetsuen_ryohifuno"
  belongs_to :tabutsurikaku , :class_name => "JyoutaiUmufukanou" , :foreign_key => "tabutsurikaku_ryohifuno"

  include Common
  after_commit :dump 
end

app/models/okunai.rb
class Okunai < ActiveRecord::Base
  belongs_to :tenkenkekka
  belongs_to :okunai_jisshi_umu , :class_name => "JyoutaiUmu" , :foreign_key => "jisshi_umu"  
  belongs_to :bundenbanhason , :class_name => "JyoutaiUmu" , :foreign_key => "bundenbanhason_umu"
  belongs_to :juudenburosyutsu , :class_name => "JyoutaiUmu" , :foreign_key => "juudenburosyutsu_umu"
  belongs_to :mijisshiriyu_list , :class_name => "RiyuOkunai" , :foreign_key => "mijisshi_riyu"

  include Common
  after_commit :dump
end

app/models/riyu_monshin.rb
class RiyuMonshin < ActiveRecord::Base
end

app/models/riyu_okunai.rb
class RiyuOkunai < ActiveRecord::Base
end

app/models/sokutei.rb
class Sokutei < ActiveRecord::Base
   belongs_to :tenkenkekka

  include Common
  after_commit :dump 
end

app/models/tenkenkekka.rb
class Tenkenkekka < ActiveRecord::Base
  belongs_to :houmon
  has_one    :monshin
  accepts_nested_attributes_for :monshin
  has_one    :okunai
  accepts_nested_attributes_for :okunai
  has_one    :okugai
  accepts_nested_attributes_for :okugai
  has_one    :sokutei
  accepts_nested_attributes_for :sokutei
  belongs_to :chosakekka  , :class_name => "ChosakekkaCode" , :foreign_key => "chosakekka_code"
  belongs_to :chosajisseki , :class_name => "ChosajissekiCode" , :foreign_key => "chosajisseki_code"

  include Common
  after_commit :dump 
end

app/models/tenki.rb
class Tenki < ActiveRecord::Base
end

app/models/zaitaku.rb
class Zaitaku < ActiveRecord::Base
end

app/models/zetsufudaicho.rb
class Zetsufudaicho < ActiveRecord::Base
end

app/controllers/chosakekka_codes_controller.rb
class ChosakekkaCodesController < ApplicationController
  before_action :set_chosakekka_code, only: [:show, :edit, :update, :destroy]

  # GET /chosakekka_codes
  # GET /chosakekka_codes.json
  def index
    @chosakekka_codes = ChosakekkaCode.all
  end

  # GET /chosakekka_codes/1
  # GET /chosakekka_codes/1.json
  def show
  end

  # GET /chosakekka_codes/new
  def new
    @chosakekka_code = ChosakekkaCode.new
  end

  # GET /chosakekka_codes/1/edit
  def edit
  end

  # POST /chosakekka_codes
  # POST /chosakekka_codes.json
  def create
    @chosakekka_code = ChosakekkaCode.new(chosakekka_code_params)

    respond_to do |format|
      if @chosakekka_code.save
        format.html { redirect_to @chosakekka_code, notice: 'Chosakekka code was successfully created.' }
        format.json { render :show, status: :created, location: @chosakekka_code }
      else
        format.html { render :new }
        format.json { render json: @chosakekka_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chosakekka_codes/1
  # PATCH/PUT /chosakekka_codes/1.json
  def update
    respond_to do |format|
      if @chosakekka_code.update(chosakekka_code_params)
        format.html { redirect_to @chosakekka_code, notice: 'Chosakekka code was successfully updated.' }
        format.json { render :show, status: :ok, location: @chosakekka_code }
      else
        format.html { render :edit }
        format.json { render json: @chosakekka_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chosakekka_codes/1
  # DELETE /chosakekka_codes/1.json
  def destroy
    @chosakekka_code.destroy
    respond_to do |format|
      format.html { redirect_to chosakekka_codes_url, notice: 'Chosakekka code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chosakekka_code
      @chosakekka_code = ChosakekkaCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chosakekka_code_params
      params.require(:chosakekka_code).permit(:atai)
    end
end

app/helpers/chosakekka_codes_helper.rb
module ChosakekkaCodesHelper
end

app/helpers/kofus_helper.rb
module KofusHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/tenkis_helper.rb
module TenkisHelper
end

app/views/chosakekka_codes/_form.html.erb
<%= form_for(@chosakekka_code) do |f| %>
  <% if @chosakekka_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chosakekka_code.errors.count, "error") %> prohibited this chosakekka_code from being saved:</h2>

      <ul>
      <% @chosakekka_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :atai %><br>
    <%= f.text_field :atai %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chosakekka_codes/edit.html.erb
<h1>Editing chosakekka_code</h1>

<%= render 'form' %>

<%= link_to 'Show', @chosakekka_code %> |
<%= link_to 'Back', chosakekka_codes_path %>

app/views/chosakekka_codes/index.html.erb
<h1>Listing chosakekka_codes</h1>

<table>
  <thead>
    <tr>
      <th>Atai</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chosakekka_codes.each do |chosakekka_code| %>
      <tr>
        <td><%= chosakekka_code.atai %></td>
        <td><%= link_to 'Show', chosakekka_code %></td>
        <td><%= link_to 'Edit', edit_chosakekka_code_path(chosakekka_code) %></td>
        <td><%= link_to 'Destroy', chosakekka_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chosakekka code', new_chosakekka_code_path %>

app/views/chosakekka_codes/new.html.erb
<h1>New chosakekka_code</h1>

<%= render 'form' %>

<%= link_to 'Back', chosakekka_codes_path %>

app/views/chosakekka_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Atai:</strong>
  <%= @chosakekka_code.atai %>
</p>

<%= link_to 'Edit', edit_chosakekka_code_path(@chosakekka_code) %> |
<%= link_to 'Back', chosakekka_codes_path %>