config/routes.rb
Rails.application.routes.draw do
  resources :eigyosyos

  root :to => 'descriptions#index'
  
  resources :zetsufudaichos

  get 'naisenchosahyou/index'

  get 'map/index'

  resources :descriptions

get 'kofus/:id/show_one' => 'kofus#show_one' , as: 'show_one'
  
  resources :riyu_okunais

  resources :riyu_monshins

  resources :chosajisseki_codes

  resources :chosakekka_codes

  resources :zaitakus

  resources :tenkis

  resources :jyoutai_umufukanous

  resources :jyoutai_umumijisshis

  resources :jyoutai_umus

  resources :sokuteis

  resources :monshins

  resources :okugais

  resources :okunais

  resources :tenkenkekkas

  resources :houmons

  resources :kofus

  resources :keiyakus
 
  resources :chosains

  get 'mikofu_keiyakus' => 'keiyakus#mikofuindex'

  post 'create_kofus' => 'kofus#addKofus'
 
  resources :logindatas, only: [:create, :destroy]
  get    '/signin(/:kyoukaicode)'  => 'logindatas#new' , as: 'signin'
  delete '/signout' => 'logindatas#destroy'

  get 'chosains/eigyosyo_mem/:code' => 'chosains#eigyosyo_mem'

end

app/models/chosain.rb
class Chosain < ActiveRecord::Base
  has_many :kofus
  belongs_to :eigyosyo, :foreign_key => 'kyoukaicode'
end

app/models/description.rb
class Description < ActiveRecord::Base
end

app/models/eigyosyo.rb
class Eigyosyo < ActiveRecord::Base
  self.primary_key="kyoukaicode"
  has_many :chosains
end

app/models/houmon.rb
class Houmon < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  belongs_to :kofu
  has_one    :tenkenkekka
  accepts_nested_attributes_for :tenkenkekka
  belongs_to :tenko  , :class_name => "Tenki" , :foreign_key => "tenki"
  belongs_to :zaitakufuzai , :class_name => "Zaitaku" , :foreign_key => "zaitaku_jotai"
  
  include Common
  after_commit :dump 
end

app/models/jyoutai_umu.rb
class JyoutaiUmu < ActiveRecord::Base
end

app/models/keiyaku.rb
class Keiyaku < ActiveRecord::Base
  has_many :kofus
end

app/models/kofu.rb
class Kofu < ActiveRecord::Base
  belongs_to :keiyaku
  belongs_to :chosain
  has_many :houmons
  belongs_to :chosajisseki , :class_name => "ChosajissekiCode" , :foreign_key => "newest_chosajisseki_code"

  include Common
  after_commit :dump
end

app/models/monshin.rb
class Monshin < ActiveRecord::Base
  belongs_to :tenkenkekka
  belongs_to :monshin_jisshi_umu , :class_name => "JyoutaiUmu" , :foreign_key => "jisshi_umu"  
  belongs_to :mononifurebiribiri_umumijisshi , :class_name => "JyoutaiUmumijisshi" , :foreign_key => "mononifurebiribiri_umumi"
  belongs_to :zokaichiku_umumijisshi , :class_name => "JyoutaiUmumijisshi" , :foreign_key => "zoukaichiku_umumi"
  belongs_to :mijisshiriyu_list , :class_name => "RiyuMonshin" , :foreign_key => "mijisshi_riyu"

  include Common
  after_commit :dump 
end

app/models/okugai.rb
class Okugai < ActiveRecord::Base
  belongs_to :tenkenkekka
  belongs_to :toritsukezetsuen , :class_name => "JyoutaiUmufukanou" , :foreign_key => "toritsukezetsuen_ryohifuno"
  belongs_to :tabutsurikaku , :class_name => "JyoutaiUmufukanou" , :foreign_key => "tabutsurikaku_ryohifuno"

  include Common
  after_commit :dump 
end

app/models/okunai.rb
class Okunai < ActiveRecord::Base
  belongs_to :tenkenkekka
  belongs_to :okunai_jisshi_umu , :class_name => "JyoutaiUmu" , :foreign_key => "jisshi_umu"  
  belongs_to :bundenbanhason , :class_name => "JyoutaiUmu" , :foreign_key => "bundenbanhason_umu"
  belongs_to :juudenburosyutsu , :class_name => "JyoutaiUmu" , :foreign_key => "juudenburosyutsu_umu"
  belongs_to :mijisshiriyu_list , :class_name => "RiyuOkunai" , :foreign_key => "mijisshi_riyu"

  include Common
  after_commit :dump
end

app/models/riyu_monshin.rb
class RiyuMonshin < ActiveRecord::Base
end

app/models/riyu_okunai.rb
class RiyuOkunai < ActiveRecord::Base
end

app/models/sokutei.rb
class Sokutei < ActiveRecord::Base
   belongs_to :tenkenkekka

  include Common
  after_commit :dump 
end

app/models/tenkenkekka.rb
class Tenkenkekka < ActiveRecord::Base
  belongs_to :houmon
  has_one    :monshin
  accepts_nested_attributes_for :monshin
  has_one    :okunai
  accepts_nested_attributes_for :okunai
  has_one    :okugai
  accepts_nested_attributes_for :okugai
  has_one    :sokutei
  accepts_nested_attributes_for :sokutei
  belongs_to :chosakekka  , :class_name => "ChosakekkaCode" , :foreign_key => "chosakekka_code"
  belongs_to :chosajisseki , :class_name => "ChosajissekiCode" , :foreign_key => "chosajisseki_code"

  include Common
  after_commit :dump 
end

app/models/tenki.rb
class Tenki < ActiveRecord::Base
end

app/models/zaitaku.rb
class Zaitaku < ActiveRecord::Base
end

app/models/zetsufudaicho.rb
class Zetsufudaicho < ActiveRecord::Base
end

app/controllers/zetsufudaichos_controller.rb
class ZetsufudaichosController < ApplicationController
  before_action :set_zetsufudaicho, only: [:show, :edit, :update, :destroy]

  # GET /zetsufudaichos
  # GET /zetsufudaichos.json
  def index
    @zetsufudaichos = Zetsufudaicho.all
  end

  # GET /zetsufudaichos/1
  # GET /zetsufudaichos/1.json
  def show
  end

  # GET /zetsufudaichos/new
  def new
    @zetsufudaicho = Zetsufudaicho.new
  end

  # GET /zetsufudaichos/1/edit
  def edit
  end

  # POST /zetsufudaichos
  # POST /zetsufudaichos.json
  def create
    @zetsufudaicho = Zetsufudaicho.new(zetsufudaicho_params)

    respond_to do |format|
      if @zetsufudaicho.save
        format.html { redirect_to @zetsufudaicho, notice: 'Zetsufudaicho was successfully created.' }
        format.json { render :show, status: :created, location: @zetsufudaicho }
      else
        format.html { render :new }
        format.json { render json: @zetsufudaicho.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zetsufudaichos/1
  # PATCH/PUT /zetsufudaichos/1.json
  def update
    respond_to do |format|
      if @zetsufudaicho.update(zetsufudaicho_params)
        format.html { redirect_to @zetsufudaicho, notice: 'Zetsufudaicho was successfully updated.' }
        format.json { render :show, status: :ok, location: @zetsufudaicho }
      else
        format.html { render :edit }
        format.json { render json: @zetsufudaicho.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zetsufudaichos/1
  # DELETE /zetsufudaichos/1.json
  def destroy
    @zetsufudaicho.destroy
    respond_to do |format|
      format.html { redirect_to zetsufudaichos_url, notice: 'Zetsufudaicho was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zetsufudaicho
      @zetsufudaicho = Zetsufudaicho.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zetsufudaicho_params
      params.require(:zetsufudaicho).permit(:keiyaku_id, :scsym, :sscsym, :sscsym2, :sscsym3, :sscsym4, :haisen, :kiki, :kaishuym, :biko)
    end
end

app/helpers/houmons_helper.rb
module HoumonsHelper
end

app/helpers/kofus_helper.rb
module KofusHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/tenkis_helper.rb
module TenkisHelper
end

app/helpers/zetsufudaichos_helper.rb
module ZetsufudaichosHelper
end

app/views/zetsufudaichos/_form.html.erb
<%= form_for(@zetsufudaicho) do |f| %>
  <% if @zetsufudaicho.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zetsufudaicho.errors.count, "error") %> prohibited this zetsufudaicho from being saved:</h2>

      <ul>
      <% @zetsufudaicho.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keiyaku_id %><br>
    <%= f.text_field :keiyaku_id %>
  </div>
  <div class="field">
    <%= f.label :scsym %><br>
    <%= f.text_field :scsym %>
  </div>
  <div class="field">
    <%= f.label :sscsym %><br>
    <%= f.text_field :sscsym %>
  </div>
  <div class="field">
    <%= f.label :sscsym2 %><br>
    <%= f.text_field :sscsym2 %>
  </div>
  <div class="field">
    <%= f.label :sscsym3 %><br>
    <%= f.text_field :sscsym3 %>
  </div>
  <div class="field">
    <%= f.label :sscsym4 %><br>
    <%= f.text_field :sscsym4 %>
  </div>
  <div class="field">
    <%= f.label :haisen %><br>
    <%= f.number_field :haisen %>
  </div>
  <div class="field">
    <%= f.label :kiki %><br>
    <%= f.text_field :kiki %>
  </div>
  <div class="field">
    <%= f.label :kaishuym %><br>
    <%= f.text_field :kaishuym %>
  </div>
  <div class="field">
    <%= f.label :biko %><br>
    <%= f.text_field :biko %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zetsufudaichos/edit.html.erb
<h1>Editing zetsufudaicho</h1>

<%= render 'form' %>

<%= link_to 'Show', @zetsufudaicho %> |
<%= link_to 'Back', zetsufudaichos_path %>

app/views/zetsufudaichos/index.html.erb
<h1>Listing zetsufudaichos</h1>

<table>
  <thead>
    <tr>
      <th>Keiyaku</th>
      <th>Scsym</th>
      <th>Sscsym</th>
      <th>Sscsym2</th>
      <th>Sscsym3</th>
      <th>Sscsym4</th>
      <th>Haisen</th>
      <th>Kiki</th>
      <th>Kaishuym</th>
      <th>Biko</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zetsufudaichos.each do |zetsufudaicho| %>
      <tr>
        <td><%= zetsufudaicho.keiyaku_id %></td>
        <td><%= zetsufudaicho.scsym %></td>
        <td><%= zetsufudaicho.sscsym %></td>
        <td><%= zetsufudaicho.sscsym2 %></td>
        <td><%= zetsufudaicho.sscsym3 %></td>
        <td><%= zetsufudaicho.sscsym4 %></td>
        <td><%= zetsufudaicho.haisen %></td>
        <td><%= zetsufudaicho.kiki %></td>
        <td><%= zetsufudaicho.kaishuym %></td>
        <td><%= zetsufudaicho.biko %></td>
        <td><%= link_to 'Show', zetsufudaicho %></td>
        <td><%= link_to 'Edit', edit_zetsufudaicho_path(zetsufudaicho) %></td>
        <td><%= link_to 'Destroy', zetsufudaicho, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zetsufudaicho', new_zetsufudaicho_path %>

app/views/zetsufudaichos/new.html.erb
<h1>New zetsufudaicho</h1>

<%= render 'form' %>

<%= link_to 'Back', zetsufudaichos_path %>

app/views/zetsufudaichos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keiyaku:</strong>
  <%= @zetsufudaicho.keiyaku_id %>
</p>

<p>
  <strong>Scsym:</strong>
  <%= @zetsufudaicho.scsym %>
</p>

<p>
  <strong>Sscsym:</strong>
  <%= @zetsufudaicho.sscsym %>
</p>

<p>
  <strong>Sscsym2:</strong>
  <%= @zetsufudaicho.sscsym2 %>
</p>

<p>
  <strong>Sscsym3:</strong>
  <%= @zetsufudaicho.sscsym3 %>
</p>

<p>
  <strong>Sscsym4:</strong>
  <%= @zetsufudaicho.sscsym4 %>
</p>

<p>
  <strong>Haisen:</strong>
  <%= @zetsufudaicho.haisen %>
</p>

<p>
  <strong>Kiki:</strong>
  <%= @zetsufudaicho.kiki %>
</p>

<p>
  <strong>Kaishuym:</strong>
  <%= @zetsufudaicho.kaishuym %>
</p>

<p>
  <strong>Biko:</strong>
  <%= @zetsufudaicho.biko %>
</p>

<%= link_to 'Edit', edit_zetsufudaicho_path(@zetsufudaicho) %> |
<%= link_to 'Back', zetsufudaichos_path %>